# Implementação do AG

Algoritmo Genético implementado em Python com uso do Numpy.

In [87]:
import numpy as np
import matplotlib.pyplot as plt

In [117]:
class AG():
    def __init__(self, TAM_POP, 
                 TAM_GENE, 
                 GERACAO = 100, 
                 TX_CRUZAMENTO = 95, 
                 TX_MUTACAO = 5, 
                 TX_ELITISMO = 0):
        
        self.TAM_POP = TAM_POP
        self.TAM_GENE = TAM_GENE
        self.GERACAO = GERACAO

        self.TX_CRUZAMENTO = TX_CRUZAMENTO
        self.TX_MUTACAO = TX_MUTACAO
        self.TX_ELITISMO = TX_ELITISMO

        self.pop = criar_pop_inicial(TAM_POP, TAM_GENE)
        self.pop_aux = criar_pop_inicial(TAM_POP, TAM_GENE)
        
    def criar_pop_inicial(self, TAM_POP, TAM_GENE):
        return np.random.randint(0, 2, [TAM_POP, TAM_GENE])

    def selecao(self, TAM_POP):
        pai1 = np.random.randint(0, TAM_POP)
        pai2 = np.random.randint(0, TAM_POP)
        while pai1 == pai2:
            pai2 = np.random.randint(0, TAM_POP)
        return [pai1, pai2]

    def mutacao(self, q):
        gene1 = np.random.randint(0, TAM_GENE)
        gene2 = np.random.randint(0, TAM_GENE)

        ind1 = pop[q[0]]
        ind2 = pop[q[1]]

        ind1[gene1] = 1 if ind1[gene1] == 0 else 0
        ind2[gene2] = 1 if ind2[gene2] == 0 else 0
        return [ind1, ind2]

    def cruzamento_simples(self, q):
        pai1 = pop[q[0]]
        pai2 = pop[q[1]]
        desc1 = np.zeros(TAM_GENE, dtype=np.int)
        desc2 = np.zeros(TAM_GENE, dtype=np.int)

        meio = int(TAM_GENE/2)
        for i in range(TAM_GENE):
            if i < meio:
                desc1[i] = pai1[i]
                desc2[i] = pai2[i]
            else:
                desc1[i] = pai2[i]
                desc2[i] = pai1[i]
        return [desc1, desc2]

    """
    Método que implementa o cruzamento composto por dois
    pontos de corte.
    args:
        q: array com duas posições referente à posições de 
        elementos na matriz pop
    return:
        [] array contendo dois novos indivíduos.
    """
    def cruzamento_composto(self, q):
        pass

    """
    Método que implementa o cruzamento uniforme.
    args:
        q: array com duas posições referente à posições de 
        elementos na matriz pop
    return:
        [] array contendo dois novos indivíduos.
    """
    def cruzamento_mascara(self, q):
        pass

    def substituicao(self):
        self.pop = self.pop_aux

    def parada(self, g):

        if g > self.GERACAO:
            return True

        return False

    def qtd_individuos(self, TAM_POP, taxa):
          return int((TAM_POP * taxa) / 100)

    def roleta(self):
        pass
    
    def avaliacao(self):
        pass
    
    def evolucao(self):
        g = 1
        while True:
            #         self.avaliacao()
            if self.parada(g):
                break

            # Cruzamento
            qtd_ind_cruzamento = self.qtd_individuos(self.TAM_POP, self.TX_CRUZAMENTO)
            qtd_cruzamento = int(qtd_ind_cruzamento/2)
            for i in range(qtd_cruzamento):
                q = self.selecao(self.TAM_POP)

                descendentes = self.cruzamento_simples(q)

                pos = (1 * i) + i
                self.pop_aux[pos] = descendentes[0]
                self.pop_aux[pos + 1] = descendentes[1]

            # Mutação
            qtd_ind_mutacao = self.qtd_individuos(self.TAM_POP, self.TX_MUTACAO)
            qtd_mutacao = int(np.ceil(qtd_ind_mutacao/2))

            for i in range(qtd_mutacao):
                q = self.selecao(self.TAM_POP)
                mutantes = self.mutacao(q)

                pos = ((1 * i) + i) + qtd_ind_cruzamento
                self.pop_aux[pos] = mutantes[0]
                if (pos + 1) < self.TAM_POP:
                    self.pop_aux[pos + 1] = mutantes[1]

            self.substituicao()
            g += 1
     

In [116]:
# Inicialização do algoritmo
ag = AG(10, 10)
ag.evolucao()


[[0 1 1 0 1 0 0 0 1 0]
 [0 1 0 0 1 1 0 1 1 0]
 [0 1 0 1 0 0 1 0 0 1]
 [0 0 0 0 0 1 0 1 1 0]
 [1 1 1 1 1 0 0 1 1 1]
 [1 1 1 1 0 0 1 1 0 1]
 [0 0 1 0 1 0 1 1 1 0]
 [1 0 0 1 0 0 0 1 1 0]
 [1 1 1 0 1 0 0 1 1 1]
 [0 0 0 0 0 1 0 0 1 1]]
0
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
22
23
24
25
26
27
28
29
30
31
32
33
34
35
36
37
38
39
40
41
42
43
44
45
46
47
48
49
50
51
52
53
54
55
56
57
58
59
60
61
62
63
64
65
66
67
68
69
70
71
72
73
74
75
76
77
78
79
80
81
82
83
84
85
86
87
88
89
90
91
92
93
94
95
96
97
98
99
100
101
[[0 1 1 0 1 0 0 0 1 0]
 [0 1 0 0 1 1 0 1 1 0]
 [0 1 0 1 0 0 1 0 0 1]
 [0 0 0 0 0 1 0 1 1 0]
 [1 1 1 1 1 0 0 1 1 1]
 [1 1 1 1 0 0 1 1 0 1]
 [0 0 1 0 1 0 1 1 1 0]
 [1 0 0 1 0 0 0 1 1 0]
 [1 1 1 0 1 0 0 1 1 1]
 [0 0 0 0 0 1 0 0 1 1]]
