# K-means Clustering

In [23]:
import numpy as np
import matplotlib.pyplot as plt

from mpl_toolkits.mplot3d import Axes3D

from sklearn.cluster import KMeans
from sklearn import datasets

from scipy import stats
np.random.seed(51)

In [24]:
iris = datasets.load_iris()
print("Type: ", type(iris.data))

print("\nDimensions: ", iris.data.shape)

print("\nHead: ", iris.data[0:3])

print("\nDescription: ", stats.describe(iris.data))

Type:  <class 'numpy.ndarray'>

Dimensions:  (150, 4)

Head:  [[5.1 3.5 1.4 0.2]
 [4.9 3.  1.4 0.2]
 [4.7 3.2 1.3 0.2]]

Description:  DescribeResult(nobs=150, minmax=(array([4.3, 2. , 1. , 0.1]), array([7.9, 4.4, 6.9, 2.5])), mean=array([5.84333333, 3.05733333, 3.758     , 1.19933333]), variance=array([0.68569351, 0.18997942, 3.11627785, 0.58100626]), skewness=array([ 0.31175306,  0.31576711, -0.27212767, -0.10193421]), kurtosis=array([-0.57356795,  0.18097632, -1.39553589, -1.33606741]))


In [18]:
X = iris.data
y = iris.target 

est = KMeans(n_clusters=3)
est.fit(X)
est.labels_

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 2, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 1, 2, 2, 2, 2, 1, 2, 2, 2,
       2, 2, 2, 1, 1, 2, 2, 2, 2, 1, 2, 1, 2, 1, 2, 2, 1, 1, 2, 2, 2, 2,
       2, 1, 2, 2, 2, 2, 1, 2, 2, 2, 1, 2, 2, 2, 1, 2, 2, 1], dtype=int32)

In [22]:
import pandas as pd
mc = pd.crosstab(iris.target, est.labels_)
mc

col_0   0   1   2
row_0            
0      50   0   0
1       0  48   2
2       0  14  36

# Como analisar a matriz confusão?

![Matriz de Confusão](img/matriz_confusao_2_class.png)

Enquanto as métricas solicitadas são dadas pelas seguintes equações:

$ Acuracia = \frac{VP + VN}{VP + VN + FP + FN} $

$ Precisao = \frac{VP}{VP + FP} $

$ Revocacao = \frac{VP}{VP + FN} $

$ Especificidade = \frac{VN}{VN + FP} $


# Temos três classes, e agora?

![MC3Class](img/matriz_confusao_3_class.png)

Fonte: https://tinyurl.com/2mnpm48x